// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:final_project/features/gathering/domain_layer/entity/gathering_entity.dart';

// Will be generated by dart_mappable
part 'gathering_model.mapper.dart';

@MappableClass(caseStyle: CaseStyle.snakeCase)
class GatheringModel extends GatheringEntity with GatheringModelMappable {
  GatheringModel(super.id, super.userId, super.title, super.description, super.city, super.date, super.address, super.imageUrl, super.category);
 
}