// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:final_project/features/gathering/domain_layer/entity/gathering_entity.dart';

// Will be generated by dart_mappable
part 'gathering_model.mapper.dart';

@MappableClass(caseStyle: CaseStyle.snakeCase)
class GatheringModel extends GatheringEntity with GatheringModelMappable {
  GatheringModel({
     String? id,
    required super.userId,
    required super.title,
    required super.description,
    required super.city,
    required super.date,
    required super.eventTime,
    required super.address,
    required super.imageUrl,
    required super.category,
    super.latitude,
    super.longitude,

  }): super(isBookmarked: false);
}
