// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:final_project/features/ai_image_analysis/domain_layer/entity/ai_landmark_analysis_entity.dart';

// Will be generated by dart_mappable
part 'ai_image_analysis_model.mapper.dart';

@MappableClass()
class AiImageAnalysisModel extends LandmarkAnalysisEntity with AiImageAnalysisModelMappable {
 
  AiImageAnalysisModel( super.text);
}
