import 'package:flutter_ai_toolkit/flutter_ai_toolkit.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:injectable/injectable.dart';

abstract class TripDataSource {
  Future<LlmProvider> initializeChatWithPrompt(String systemPrompt);
}

@LazySingleton(as: TripDataSource)
class TripRemoteDataSource implements TripDataSource {
  // Get the gemini API key from the .env
  final String _apiKey = dotenv.env['GeminiAPIKey']!;

  @override
  Future<LlmProvider> initializeChatWithPrompt(String systemPrompt) async {
    final model = GenerativeModel(model: 'gemini-2.5-flash', apiKey: _apiKey);

    try {
      final content = [Content.text(systemPrompt)];
      // The response generated by the model from the prompt given 
      final response = await model.generateContent(content);
      final aiResponseText = response.text ?? "Failed to generate plan.";
      return GeminiProvider(
        model: model,
        // To dispay the model response, not the user prompt.. we check the history and compare user vs model message 
        history: [
          ChatMessage(
            origin: MessageOrigin.llm,
            text: aiResponseText,
            attachments: [],
          ),
        ],
      );
    } catch (e) {
      throw Exception("Failed to contact AI: $e");
    }
  }
}
